spring:
  application:
    name: support-ticket-system
  # Cloud SQL (PostgreSQL) configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    # For local development
    url: jdbc:postgresql://localhost:5432/support_ticket_db
    username: postgres
    password: postgres
    # For Cloud SQL
    # url: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${DB_USERNAME}&password=${DB_PASSWORD}
    # username: ${DB_USERNAME}
    # password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  # Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  # Mail configuration (for Gmail/SMTP)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:no-reply@example.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:default_dev_secret_key_should_be_changed_in_production_environment}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  issuer: support-ticket-system

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
  exposed-headers: Authorization
  allow-credentials: true
  max-age: 3600

# GCP Configuration
gcp:
  # Project Configuration
  project-id: ${GCP_PROJECT_ID:support-ticket-system}
  credentials:
    use-default: ${GCP_USE_DEFAULT_CREDENTIALS:true}
    path: ${GCP_CREDENTIALS_PATH:}

  # Google Cloud Storage Configuration
  storage:
    bucket-name: ${GCP_STORAGE_BUCKET_NAME:support-ticket-system-files}
    signed-url-expiration: ${GCP_STORAGE_SIGNED_URL_EXPIRATION:3600}
    public-bucket: ${GCP_STORAGE_PUBLIC_BUCKET:false}
    folders:
      attachments: ${GCP_STORAGE_FOLDER_ATTACHMENTS:attachments}
      profiles: ${GCP_STORAGE_FOLDER_PROFILES:profiles}
      tickets: ${GCP_STORAGE_FOLDER_TICKETS:tickets}
      temp: ${GCP_STORAGE_FOLDER_TEMP:temp}
    max-file-size: ${GCP_STORAGE_MAX_FILE_SIZE:10485760} # 10MB
    allowed-file-types: ${GCP_STORAGE_ALLOWED_FILE_TYPES:jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,txt,csv,zip}

  # Secret Manager Configuration
  secret-manager:
    cache-ttl-seconds: ${GCP_SECRET_MANAGER_CACHE_TTL_SECONDS:300}
    paths:
      secrets: ${GCP_SECRET_MANAGER_PATH_SECRETS:secrets/}
      config: ${GCP_SECRET_MANAGER_PATH_CONFIG:config/}
      api-keys: ${GCP_SECRET_MANAGER_PATH_API_KEYS:api-keys/}
      feature-flags: ${GCP_SECRET_MANAGER_PATH_FEATURE_FLAGS:feature-flags/}

# Spring Mail Configuration (for Gmail/SMTP) is added to the main spring section

# Twilio Configuration for SMS
twilio:
  enabled: ${TWILIO_ENABLED:false}
  account-sid: ${TWILIO_ACCOUNT_SID:}
  auth-token: ${TWILIO_AUTH_TOKEN:}
  phone-number: ${TWILIO_PHONE_NUMBER:}

# OpenAI API Configuration
openai:
  api:
    key: ${OPENAI_API_KEY:}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    model: ${OPENAI_API_MODEL:gpt-4o}

# ChatGPT CLI Configuration
chatgpt:
  cli:
    enabled: ${CHATGPT_CLI_ENABLED:false}

# Registration Configuration
registration:
  # Email verification required
  email-verification-required: ${REGISTRATION_EMAIL_VERIFICATION_REQUIRED:false}
  # SMS verification required
  sms-verification-required: ${REGISTRATION_SMS_VERIFICATION_REQUIRED:false}
  # Default roles
  default-user-role: USER
  default-client-role: CLIENT
  default-expert-role: EXPERT

# WebSocket Configuration
websocket:
  # Basic Configuration
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,https://support.example.com}
  endpoint: ${WEBSOCKET_ENDPOINT:/ws}
  topic-prefix: ${WEBSOCKET_TOPIC_PREFIX:/topic}
  queue-prefix: ${WEBSOCKET_QUEUE_PREFIX:/queue}
  app-prefix: ${WEBSOCKET_APP_PREFIX:/app}

  # Message Configuration
  message:
    max-size: ${WEBSOCKET_MESSAGE_MAX_SIZE:65536}
    trace-enabled: ${WEBSOCKET_MESSAGE_TRACE_ENABLED:false}
    buffer-size-per-session: ${WEBSOCKET_MESSAGE_BUFFER_SIZE_PER_SESSION:1024}
  send-buffer-size: ${WEBSOCKET_SEND_BUFFER_SIZE:524288}
  send-time-limit: ${WEBSOCKET_SEND_TIME_LIMIT:15000}

  # STOMP Broker Relay Configuration (for production with external message broker)
  broker-relay:
    enabled: ${WEBSOCKET_BROKER_RELAY_ENABLED:false}
    host: ${WEBSOCKET_BROKER_RELAY_HOST:localhost}
    port: ${WEBSOCKET_BROKER_RELAY_PORT:61613}
    username: ${WEBSOCKET_BROKER_RELAY_USERNAME:guest}
    password: ${WEBSOCKET_BROKER_RELAY_PASSWORD:guest}
    virtual-host: ${WEBSOCKET_BROKER_RELAY_VIRTUAL_HOST:/}
    heartbeat:
      client: ${WEBSOCKET_BROKER_RELAY_HEARTBEAT_CLIENT:10000}
      server: ${WEBSOCKET_BROKER_RELAY_HEARTBEAT_SERVER:10000}

  # Security Configuration
  security:
    require-authentication: ${WEBSOCKET_SECURITY_REQUIRE_AUTH:true}
    admin-topics-role: ${WEBSOCKET_SECURITY_ADMIN_TOPICS_ROLE:ROLE_ADMIN}
    support-topics-role: ${WEBSOCKET_SECURITY_SUPPORT_TOPICS_ROLE:ROLE_SUPPORT}

  # Endpoints Configuration
  endpoints:
    chat: ${WEBSOCKET_ENDPOINTS_CHAT:/chat}
    notifications: ${WEBSOCKET_ENDPOINTS_NOTIFICATIONS:/notifications}
    tickets: ${WEBSOCKET_ENDPOINTS_TICKETS:/tickets}
    admin: ${WEBSOCKET_ENDPOINTS_ADMIN:/admin}

  # AI Chat Configuration
  ai:
    enabled: ${WEBSOCKET_AI_ENABLED:true}
    default-model: ${WEBSOCKET_AI_DEFAULT_MODEL:gpt-3.5-turbo}
    timeout: ${WEBSOCKET_AI_TIMEOUT:30000}
    max-tokens: ${WEBSOCKET_AI_MAX_TOKENS:1000}
    temperature: ${WEBSOCKET_AI_TEMPERATURE:0.7}
    models:
      - id: gpt-3.5-turbo
        name: GPT-3.5 Turbo
        provider: openai
        enabled: ${WEBSOCKET_AI_MODEL_GPT35_ENABLED:true}
      - id: gpt-4
        name: GPT-4
        provider: openai
        enabled: ${WEBSOCKET_AI_MODEL_GPT4_ENABLED:true}
      - id: claude-2
        name: Claude 2
        provider: anthropic
        enabled: ${WEBSOCKET_AI_MODEL_CLAUDE2_ENABLED:false}
      - id: gemini-pro
        name: Gemini Pro
        provider: google
        enabled: ${WEBSOCKET_AI_MODEL_GEMINI_ENABLED:false}
      - id: custom
        name: Deepseek Chat
        provider: deepseek
        enabled: ${WEBSOCKET_AI_MODEL_DEEPSEEK_ENABLED:true}

# AI Provider Configuration
ai:
  openai:
    api-key: ${AI_OPENAI_API_KEY:}
    endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions}
  anthropic:
    api-key: ${AI_ANTHROPIC_API_KEY:}
    endpoint: ${AI_ANTHROPIC_ENDPOINT:https://api.anthropic.com/v1/messages}
  google:
    api-key: ${AI_GOOGLE_API_KEY:}
    endpoint: ${AI_GOOGLE_ENDPOINT:https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent}
  deepseek:
    api-key: ${AI_DEEPSEEK_API_KEY:}
    endpoint: ${AI_DEEPSEEK_ENDPOINT:https://api.deepseek.com/v1/chat/completions}

# Firebase Configuration
firebase:
  enabled: ${FIREBASE_ENABLED:true}
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH:firebase-service-account.json}
  database:
    url: ${FIREBASE_DATABASE_URL:}

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  credentials:
    use-default: ${AWS_USE_DEFAULT_CREDENTIALS:true}
  s3:
    bucket-name: ${AWS_S3_BUCKET:support-ticket-system-files}
    endpoint: ${AWS_S3_ENDPOINT:}
    presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:3600}
  ssm:
    parameter-path: ${AWS_SSM_PARAMETER_PATH:/support-ticket-system}
    cache-ttl-seconds: ${AWS_SSM_CACHE_TTL:300}
    preload-parameters: ${AWS_SSM_PRELOAD:false}
  ses:
    endpoint: ${AWS_SES_ENDPOINT:}
    from-email: ${AWS_SES_FROM_EMAIL:no-reply@example.com}
    reply-to-email: ${AWS_SES_REPLY_TO_EMAIL:}

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  server:
    url: ${SPRINGDOC_SERVER_URL:http://localhost:8080}
  show-actuator: true
  packages-to-scan: com.planb.supportticket.controller
  paths-to-match: /api/**

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.planb.supportticket: DEBUG
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/support_ticket_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true

# Development-specific logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.planb.supportticket: DEBUG

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    # Cloud SQL connection
    url: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # Connection pool settings
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000 # 20 seconds
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1200000 # 20 minutes
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # More conservative setting for production

# Production-specific server settings
server:
  port: ${PORT:8080}

# Production-specific logging
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: ERROR
    com.planb.supportticket: INFO
  file:
    name: /var/log/support-ticket-system.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

# Production-specific CORS settings
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
