package com.planb.supportticket.entity.enums;

public enum ExpertSpecialization {
    SOFTWARE_DEVELOPMENT,
    NETWORK_INFRASTRUCTURE,
    DATABASE_MANAGEMENT,
    CLOUD_SERVICES,
    CYBERSECURITY,
    MOBILE_DEVELOPMENT,
    WEB_DEVELOPMENT,
    DEVOPS,
    MACHINE_LEARNING,
    BUSINESS_INTELLIGENCE,
    GENERAL_IT
}
